sudo: false

language: c
cache: ccache

env:
  - KVER=4.15
  - KVER=4.16
  - KVER=4.17
  - KVER=4.18
  - KVER=4.19
  - KVER=4.20
  - KVER=5.0
  - KVER=5.1
  - KVER=5.2
  - KVER=5.3
  - KVER=5.4
  - KVER=5.5
  - KVER=5.6
  - KVER=5.7
  - KVER=5.8
  - KVER=5.9
  - KVER=master

services:
  - docker

matrix:
  allow_failures:
    - env: KVER=master
  include:
    - env: StyleCheck
      script: ./ci/run_style_check
    - env:
        - CentOS_8_Test="" EL8_MODULE_VERSION=1.8.0
      before_install:
        - echo 'DOCKER_OPTS="-H tcp://127.0.0.1:2375 -H unix:///var/run/docker.sock -s devicemapper"' | sudo tee /etc/default/docker > /dev/null
        - sudo service docker restart
        - sleep 5
        - sudo docker pull centos:8
      script:
        - sudo -E docker run --rm=true --env EL8_MODULE_VERSION=1.8.0 -v `pwd`:/base-src:rw -t centos:8 /bin/bash -c "/base-src/ci/run_centos8_test ${EL8_MODULE_VERSION}"

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - bc
      - g++-5
      - libdrm-dev
      - libelf-dev

script:
  - CC=gcc-5 ./ci/build_against_kernel ${KVER}
